name: Python package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - run: echo "Start download dependency..."
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
    
      - run: echo "Start run python program..."
      - run: python3 main.py
      - run: pytest tests.py --doctest-modules --junitxml=junit/test-results.xml

      - run: echo "Start tests..."
      - uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }} 
